M48
; DRILL file {KiCad 8.0.0-8.0.0-1~ubuntu22.04.1} date 2024-03-31T18:48:55+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-31T18:48:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-8.0.0-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.2811Y-5.2504
X4.5929Y-5.2504
M30
